### ISSUE TITLE
CircularMapper does not modify BAM headers correctly: mapDamage and GATK warnings

### ISSUE THREAD

**Issue by sc13-bioinf** [apeltzer/CircularMapper#1]
The CircularMapper method just
modifies the header of the resulting "rewrapped" BAM file to match the
original, unmodified reference genome. Apparently, this is not done
entirely correct in some cases which is why mapDamage and GATK complain
about this.

**Comment by apeltzer** [comment]
Investigating this, waiting for reply ....

**Comment by apeltzer** [comment]
Fixed in #2
