### ISSUE TITLE
Issue with building 

### ISSUE THREAD

**Issue by bamorim-bio** [apeltzer/CircularMapper#12]
Hi! I'm trying to build CircularMapper and I can't get past this error. Do you know how I can fix this? 

(assembly) beatrizamorim@cpereira CircularMapper % gradle build --warning-mode all

> Configure project :
The RepositoryHandler.jcenter() method has been deprecated. This is scheduled to be removed in Gradle 8.0. JFrog announced JCenter's sunset in February 2021. Use mavenCentral() instead. Consult the upgrading guide for further information: https://docs.gradle.org/7.3.1/userguide/upgrading_version_6.html#jcenter_deprecation
        at build_9tg1l9xh9fy3jlipt0a0x3zn1$_run_closure1$_closure2.doCall(/Users/beatrizamorim/Desktop/mtDNA/CircularMapper/build.gradle:7)
        (Run with --stacktrace to get the full stack trace of this deprecation warning.)

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/beatrizamorim/Desktop/mtDNA/CircularMapper/build.gradle' line: 19

* What went wrong:
A problem occurred evaluating root project 'CircularMapper'.
> Plugin with id 'maven' not found.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

**Comment by apeltzer** [comment]
Hi Beatriz! Guess my gradle scripts are not working with newer gradle releases anymore. I will see what I can do with this, but you can always rely on the existing binaries and/or the bioconda package https://anaconda.org/bioconda/circularmapper for now at least

**Comment by bamorim-bio** [comment]
Hi Alexander, thanks! I was able to run the program with the binaries :)

Just a stupid question but how do you call circularmapper using conda? 

(assembly) beatrizamorim@MacBook-Pro ~ % conda list
# packages in environment at /Users/beatrizamorim/opt/anaconda3/envs/assembly:
#
# Name                    Version                   Build  Channel
bcftools                  1.8                  h4da6232_3    bioconda
bwa                       0.7.17               h188c3c3_8    bioconda
bzip2                     1.0.8                h0d85af4_4    conda-forge
c-ares                    1.18.1               h0d85af4_0    conda-forge
ca-certificates           2021.10.26           hecd8cb5_2  
certifi                   2020.6.20          pyhd3eb1b0_3  
circularmapper            1.93.5               h4a94de4_1    bioconda

(assembly) beatrizamorim@MacBook-Pro ~ % circularmapper
zsh: command not found: circularmapper

**Comment by apeltzer** [comment]
`realignsamfile` and/or `circulargenerator` are the tool bits that you need to run ;-)
